import {MENU,items,money,subtotal,phone,orderText,smsLink} from './menu.mjs';
const cart={};let filter='All',message='',toastTimer;
const $=s=>document.querySelector(s),form=$('#order-form'),dialog=$('#review-dialog');
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600);}
function renderMenu(){const focused=document.activeElement;const action=focused?.dataset.action,id=focused?.dataset.id;$('#menu-list').innerHTML=MENU.map((m,i)=>({...m,index:i})).filter(m=>filter==='All'||filter===m.category).map(m=>`<article class="dish"><span class="dish-number">${String(m.index+1).padStart(2,'0')}</span><div><h3>${m.name}</h3><p>${m.category}</p></div><div class="dish-bottom"><span class="price">${money(m.price)}</span><div class="quantity"><button type="button" data-action="minus" data-id="${m.id}" aria-label="Remove one ${m.name}" ${!cart[m.id]?'disabled':''}>−</button><output aria-label="${m.name} quantity">${cart[m.id]||0}</output><button type="button" class="plus" data-action="plus" data-id="${m.id}" aria-label="Add ${m.name}" ${cart[m.id]>=20?'disabled':''}>+</button></div></div></article>`).join('');if(id&&action)document.querySelector(`[data-action="${action}"][data-id="${id}"]:not(:disabled)`)?.focus({preventScroll:true});}
function renderCart(){const selected=items(cart),count=selected.reduce((n,m)=>n+m.qty,0);$('#cart-lines').innerHTML=selected.length?selected.map(m=>`<div class="cart-line"><div><strong>${m.qty} × ${m.name}</strong><small>${money(m.price)} each</small><br><button type="button" class="remove" data-action="remove" data-id="${m.id}">Remove ${m.name}</button></div><span>${money(m.qty*m.price)}</span></div>`).join(''):'<p class="empty">Your ticket starts here.<br>Choose a plate from the menu.</p>';$('#subtotal').textContent=money(subtotal(cart));$('#nav-count').textContent=count;$('#mobile-count').textContent=count;$('#mobile-total').textContent=money(subtotal(cart))+'';}
function update(){renderMenu();renderCart();$('#form-error').textContent='';message='';$('#sms-link').removeAttribute('href');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(t=>t.setAttribute('aria-pressed',String(t.dataset.filter===filter)));renderMenu();return;}const id=b.dataset.id;if(!MENU.some(m=>m.id===id))return;const before=cart[id]||0;if(b.dataset.action==='plus')cart[id]=Math.min(20,before+1);if(b.dataset.action==='minus')cart[id]=Math.max(0,before-1);if(b.dataset.action==='remove')delete cart[id];update();const qty=items(cart).reduce((n,m)=>n+m.qty,0);toast(`${qty} ${qty===1?'plate':'plates'} on your ticket · ${money(subtotal(cart))}`);});
function dateToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
$('#order-date').value=dateToday();$('#order-date').min=dateToday();
form.addEventListener('change',()=>{const delivery=form.elements.method.value==='Delivery';$('#address-field').hidden=!delivery;form.elements.address.required=delivery;form.elements.address.disabled=!delivery;form.elements.phone.setCustomValidity('');});
form.addEventListener('input',()=>{form.elements.phone.setCustomValidity('');$('#form-error').textContent='';message='';});
form.addEventListener('submit',e=>{e.preventDefault();$('#form-error').textContent='';if(!items(cart).length){$('#form-error').textContent='Choose at least one plate from the menu before reviewing your text.';return;}if(!phone(form.elements.phone.value)){form.elements.phone.setCustomValidity('Enter a 10-digit US mobile number, with optional +1.');form.elements.phone.reportValidity();return;}const customer=Object.fromEntries(new FormData(form));if(customer.date<dateToday()){$('#form-error').textContent='Choose today or a future date.';return;}if(!customer.time.trim()){$('#form-error').textContent='Add your preferred time.';return;}try{message=orderText(cart,customer);}catch(err){$('#form-error').textContent=err.message;return;}$('#message-preview').value=message;const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);$('#sms-link').href=smsLink(message,ios);$('#send-status').textContent='Nothing has been sent. Review your message and press Send in your messaging app.';$('#copy-text').textContent='Copy order text';dialog.showModal();});
$('#sms-link').addEventListener('click',e=>{if(!message){e.preventDefault();return;}$('#send-status').textContent='Your messaging app should open. Press Send there. This site cannot verify delivery or confirm your order. If nothing opens, copy the text and send it to 267-602-3346.';});
$('#copy-text').onclick=async()=>{try{await navigator.clipboard.writeText(message);$('#copy-text').textContent='Copied';$('#send-status').textContent='Order copied. Paste it into a text to 267-602-3346, then press Send. Nothing has been sent by this site.';}catch{$('#message-preview').focus();$('#message-preview').select();$('#send-status').textContent='Select and copy the message above, then paste it into a text to 267-602-3346.';}};
$('#close-review').onclick=$('#edit-order').onclick=()=>dialog.close();
$('#details-link').addEventListener('click',()=>{if(!items(cart).length)toast('Choose your plates first, then fill out your details.');});
form.elements.address.disabled=true;form.hidden=false;renderMenu();renderCart();
