import {missions} from './curriculum.mjs';
export const KEY='innerg.learn-earn.demo.v1';
export const initialState=()=>({version:1,records:{},assigned:'inflation',rewards:[{id:'pick',name:'Choose the family activity',cost:50},{id:'creative',name:'Creative project time together',cost:100},{id:'outing',name:'Plan a weekend outing',cost:200}],requests:[]});
export const balance=s=>Object.entries(s.records).reduce((sum,[id,r])=>sum+(r.status==='approved'?(missions.find(m=>m.id===id)?.points||0):0),0)-s.requests.filter(r=>r.status!=='declined').reduce((sum,r)=>sum+r.cost,0);
export function streak(s,now=new Date()) {const days=new Set(Object.values(s.records).filter(r=>r.status==='approved').map(r=>r.approvedDay));let day=new Date(now.getFullYear(),now.getMonth(),now.getDate());const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(!days.has(key(day)))day.setDate(day.getDate()-1);let n=0;while(days.has(key(day))){n++;day.setDate(day.getDate()-1);}return n;}
export function saveAnswer(s,id,answer){if(!missions.some(m=>m.id===id))return false;const old=s.records[id];if(old&&['pending','approved'].includes(old.status))return false;s.records[id]={...old,answer:answer.slice(0,600),status:'draft'};return true;}
export function submitProof(s,id,choice){const m=missions.find(m=>m.id===id),r=s.records[id];if(!m||!r||r.status==='approved'||r.status==='pending')return false;if(r.answer.trim().split(/\s+/).length<8||choice!==m.correct)return false;r.status='pending';r.choice=choice;r.submittedAt=new Date().toISOString();return true;}
export function review(s,id,approve){const r=s.records[id];if(r?.status!=='pending')return false;r.status=approve?'approved':'revision';if(approve){const d=new Date();r.approvedDay=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}return true;}
export function requestReward(s,id){const r=s.rewards.find(r=>r.id===id);if(!r||balance(s)<r.cost||s.requests.some(q=>q.rewardId===id&&q.status==='pending'))return false;s.requests.push({id:crypto.randomUUID(),rewardId:id,name:r.name,cost:r.cost,status:'pending'});return true;}
export function reviewReward(s,id,approve){const r=s.requests.find(r=>r.id===id);if(r?.status!=='pending')return false;r.status=approve?'approved':'declined';return true;}
export function loadState(raw){try{const s=JSON.parse(raw);if(s?.version!==1||!s.records||Array.isArray(s.records)||!Array.isArray(s.rewards)||!Array.isArray(s.requests))return initialState();for(const [id,r]of Object.entries(s.records))if(!missions.some(m=>m.id===id)||!r||typeof r.answer!=='string'||!['draft','revision','pending','approved'].includes(r.status))return initialState();if(!s.rewards.every(r=>typeof r.id==='string'&&typeof r.name==='string'&&Number.isInteger(r.cost)&&r.cost>=10&&r.cost<=10000)||!s.requests.every(r=>typeof r.id==='string'&&typeof r.name==='string'&&Number.isInteger(r.cost)&&r.cost>=10&&['pending','approved','declined'].includes(r.status)))return initialState();if(!missions.some(m=>m.id===s.assigned))s.assigned='inflation';return s;}catch{return initialState();}}
